### ISSUE TITLE
Semaphore.lock fails if a block's not given

### ISSUE THREAD

**Issue by fmitchell-r7** [rapid7/daemon_runner#35]
If [Semaphore.lock](https://github.com/rapid7/daemon_runner/blob/0.4.1/lib/daemon_runner/semaphore.rb#L17-L34) is never given a block, it won't create a new thread to renew the lock. This makes [the call to `lock_thr.kill`](https://github.com/rapid7/daemon_runner/blob/0.4.1/lib/daemon_runner/semaphore.rb#L31) fail with a `NoMethodError`.

Running `rake test` on v0.4.1 gives me this error
```
SemaphoreTest#test_can_get_two_uniq_lock_sessions:
NoMethodError: undefined method `kill' for nil:NilClass
    lib/daemon_runner/semaphore.rb:31:in `lock'
    test/daemon_runner/semaphore_test.rb:114:in `test_can_get_two_uniq_lock_sessions'
```

**Comment by fmitchell-r7** [comment]
@athompson-r7, I'm not sure if the right fix here is to move [the `semaphore.renew` call](https://github.com/rapid7/daemon_runner/blob/0.4.1/lib/daemon_runner/semaphore.rb#L21-L24) outside the if condition
```ruby
lock_thr = semaphore.renew
yield if block_given?
```
or to handle [the case where `lock_thr` might be `nil`](https://github.com/rapid7/daemon_runner/blob/0.4.1/lib/daemon_runner/semaphore.rb#L31)
```ruby
lock_thr.kill unless lock_thr.nil?
```
or both?
